package implementation

import other.T_common_conf

class T_middleware_conf extends T_common_conf {

    static String GC_MIDDLEWARE_CLASSES_CONF
    static String GC_BLACK_BOX_CONFIG
    static String GC_THREAD_CONFIG_FILE_NAME
    static String GC_REQUEST_METHOD_INTERNAL
    static String GC_USER_AGENT_INTERNAL
    static String GC_ACCEPT_LANGUAGE_INTERNAL
    static String GC_ACCEPT_LANGUAGE_EXTERNAL
    static String GC_CONTENT_TYPE_INTERNAL
    static String GC_CONTENT_TYPE_EXTERNAL
    static String GC_HOST_NAME_INTERNAL
    static String GC_UNSERCURE_TEST_TLS_SSL_MODE_INTERNAL
    static String GC_ENDPOINT_INTERNAL
    static String GC_JSON_INDENT
    static String GC_SOAP_USER
    static String GC_SOAP_PASSWORD
    static String GC_SOAP_IP
    static String GC_SOAP_SOURCE
    static String GC_SOAP_API_VERSION
    static String GC_KEYSTORE_TYPE
    static String GC_KEYSTORE_PATH
    static String GC_KEYSTORE_PASSWORD
    static String GC_JWT_KEYSTORE_TYPE
    static String GC_JWT_KEYSTORE_PATH
    static String GC_JWT_KEYSTORE_PASSWORD
    static String GC_JWT_KEYSTORE_ALIAS
    static String GC_JAVAX_DEBUG
    static String GC_SOAPACTION_HEADER_PREFIX
    static String GC_XML_TEMPLATES_PATH
    static String GC_JSON_TEMPLATES_PATH
    static String GC_TEMPLATE_FILENAME_EXTENSION
    static String GC_TYPES_PATH
    static String GC_DYNAMIC_TOKEN_CODE
    static Closure GC_DYNAMIC_TOKEN_CODE_CLOSURE
    static String GC_ROUTING_MODULE_NAME
    static String GC_ROUTING_MODULE_PATH
    static String GC_MIDDLEWARE_PACKAGE_TOKEN
    static String GC_MIDDLEWARE_PACKAGE_NAME
    static String GC_SERVICE_MODULES_PATH
    static String GC_NO_JWT_SERVICES
    static String GC_JWT_TEST_MODE
    static String GC_TEST_TRACE_MODE
    static String GC_COMPOSITE_SERVICES_PATH

    T_middleware_conf(String i_conf_file_name) {
        super(i_conf_file_name)
        GC_MIDDLEWARE_CLASSES_CONF = GC_CONST_CONF.GC_MIDDLEWARE_CLASSES_CONF(GC_MIDDLEWARE_CLASSES_CONF)
        GC_BLACK_BOX_CONFIG = GC_CONST_CONF.GC_BLACK_BOX_CONFIG(GC_BLACK_BOX_CONFIG)
        GC_THREAD_CONFIG_FILE_NAME = GC_CONST_CONF.GC_THREAD_CONFIG_FILE_NAME(GC_THREAD_CONFIG_FILE_NAME)
        GC_REQUEST_METHOD_INTERNAL = GC_CONST_CONF.GC_REQUEST_METHOD_INTERNAL(GC_REQUEST_METHOD_INTERNAL)
        GC_USER_AGENT_INTERNAL = GC_CONST_CONF.GC_USER_AGENT_INTERNAL(GC_USER_AGENT_INTERNAL)
        GC_ACCEPT_LANGUAGE_INTERNAL = GC_CONST_CONF.GC_ACCEPT_LANGUAGE_INTERNAL(GC_ACCEPT_LANGUAGE_INTERNAL)
        GC_CONTENT_TYPE_INTERNAL = GC_CONST_CONF.GC_CONTENT_TYPE_INTERNAL(GC_CONTENT_TYPE_INTERNAL)
        GC_CONTENT_TYPE_EXTERNAL = GC_CONST_CONF.GC_CONTENT_TYPE_EXTERNAL(GC_CONTENT_TYPE_EXTERNAL)
        GC_HOST_NAME_INTERNAL = GC_CONST_CONF.GC_HOST_NAME_INTERNAL(GC_HOST_NAME_INTERNAL)
        GC_UNSERCURE_TEST_TLS_SSL_MODE_INTERNAL = GC_CONST_CONF.GC_UNSERCURE_TEST_TLS_SSL_MODE_INTERNAL(GC_UNSERCURE_TEST_TLS_SSL_MODE_INTERNAL)
        GC_ENDPOINT_INTERNAL = GC_CONST_CONF.GC_ENDPOINT_INTERNAL(GC_ENDPOINT_INTERNAL)
        GC_JSON_INDENT = GC_CONST_CONF.GC_JSON_INDENT(GC_JSON_INDENT)
        GC_SOAP_USER = GC_CONST_CONF.GC_SOAP_USER(GC_SOAP_USER)
        GC_SOAP_PASSWORD = GC_CONST_CONF.GC_SOAP_PASSWORD(GC_SOAP_PASSWORD)
        GC_SOAP_IP = GC_CONST_CONF.GC_SOAP_IP(GC_SOAP_IP)
        GC_SOAP_SOURCE = GC_CONST_CONF.GC_SOAP_SOURCE(GC_SOAP_SOURCE)
        GC_SOAP_API_VERSION = GC_CONST_CONF.GC_SOAP_API_VERSION(GC_SOAP_API_VERSION)
        GC_KEYSTORE_TYPE = GC_CONST_CONF.GC_KEYSTORE_TYPE(GC_KEYSTORE_TYPE)
        GC_KEYSTORE_PATH = GC_CONST_CONF.GC_KEYSTORE_PATH(GC_KEYSTORE_PATH)
        GC_KEYSTORE_PASSWORD = GC_CONST_CONF.GC_KEYSTORE_PASSWORD(GC_KEYSTORE_PASSWORD)
        GC_JAVAX_DEBUG = GC_CONST_CONF.GC_JAVAX_DEBUG(GC_JAVAX_DEBUG)
        GC_SOAPACTION_HEADER_PREFIX = GC_CONST_CONF.GC_SOAPACTION_HEADER_PREFIX(GC_SOAPACTION_HEADER_PREFIX)
        GC_XML_TEMPLATES_PATH = GC_CONST_CONF.GC_XML_TEMPLATES_PATH(GC_XML_TEMPLATES_PATH)
        GC_TEMPLATE_FILENAME_EXTENSION = GC_CONST_CONF.GC_TEMPLATE_FILENAME_EXTENSION(GC_TEMPLATE_FILENAME_EXTENSION)
        GC_TYPES_PATH = GC_CONST_CONF.GC_TYPES_PATH(GC_TYPES_PATH)
        GC_DYNAMIC_TOKEN_CODE = GC_CONST_CONF.GC_DYNAMIC_TOKEN_CODE(GC_DYNAMIC_TOKEN_CODE)
        GC_ROUTING_MODULE_NAME = GC_CONST_CONF.GC_ROUTING_MODULE_NAME(GC_ROUTING_MODULE_NAME)
        GC_ROUTING_MODULE_PATH = GC_CONST_CONF.GC_ROUTING_MODULE_PATH(GC_ROUTING_MODULE_PATH)
        GC_MIDDLEWARE_PACKAGE_TOKEN = GC_CONST_CONF.GC_MIDDLEWARE_PACKAGE_TOKEN(GC_MIDDLEWARE_PACKAGE_TOKEN)
        GC_MIDDLEWARE_PACKAGE_NAME = GC_CONST_CONF.GC_MIDDLEWARE_PACKAGE_NAME(GC_MIDDLEWARE_PACKAGE_NAME)
        GC_SERVICE_MODULES_PATH = GC_CONST_CONF.GC_SERVICE_MODULES_PATH(GC_SERVICE_MODULES_PATH)
        GC_JSON_TEMPLATES_PATH = GC_CONST_CONF.GC_JSON_TEMPLATES_PATH(GC_JSON_TEMPLATES_PATH)
        GC_JWT_KEYSTORE_TYPE = GC_CONST_CONF.GC_JWT_KEYSTORE_TYPE(GC_JWT_KEYSTORE_TYPE)
        GC_JWT_KEYSTORE_PATH = GC_CONST_CONF.GC_JWT_KEYSTORE_PATH(GC_JWT_KEYSTORE_PATH)
        GC_JWT_KEYSTORE_PASSWORD = GC_CONST_CONF.GC_JWT_KEYSTORE_PASSWORD(GC_JWT_KEYSTORE_PASSWORD)
        GC_JWT_KEYSTORE_ALIAS = GC_CONST_CONF.GC_JWT_KEYSTORE_ALIAS(GC_JWT_KEYSTORE_ALIAS)
        GC_NO_JWT_SERVICES = GC_CONST_CONF.GC_NO_JWT_SERVICES(GC_NO_JWT_SERVICES)
        GC_JWT_TEST_MODE = GC_CONST_CONF.GC_JWT_TEST_MODE(GC_JWT_TEST_MODE)
        GC_TEST_TRACE_MODE = GC_CONST_CONF.GC_TEST_TRACE_MODE(GC_TEST_TRACE_MODE)
        GC_COMPOSITE_SERVICES_PATH = GC_CONST_CONF.GC_COMPOSITE_SERVICES_PATH(GC_COMPOSITE_SERVICES_PATH)
    }

}
